### ISSUE TITLE
Runtime error in theoretical interval computation

### ISSUE THREAD

**Issue by sertansenturk** [hsercanatli/symbtrsynthesis#17]
Some of the scores give an error in Dunya:

http://dunya.compmusic.upf.edu/document/manager/collection/makam-symbtr/e25b247d-bb79-4c40-999a-15c822f15a68/75
http://dunya.compmusic.upf.edu/document/manager/collection/makam-symbtr/86e85142-3964-4070-a1a6-59a6606bec26/75
http://dunya.compmusic.upf.edu/document/manager/collection/makam-symbtr/90516943-fb05-4b31-9133-fbbd63dda0e0/75

The error message is:
```python
  Traceback (most recent call last):
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/__init__.py", line 137, in process_document
    return self.run(musicbrainzid, fname)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/makam/scoresynthesis.py", line 65, in run
    bpm, measures, tnc_sym, symbtr_slug, mbid)
  File "/srv/dunya/env/src/pycompmusic/compmusic/extractors/makam/scoresynthesis.py", line 81, in synth
    tonic_sym=tnc_sym, synth_type='karplus', verbose=True)
  File "/srv/dunya/env/local/lib/python2.7/site-packages/symbtrsynthesis/adaptivesynthesizer.py", line 100, in synth_from_tuning
    tonic_sym)
  File "/srv/dunya/env/local/lib/python2.7/site-packages/symbtrsynthesis/adaptivesynthesizer.py", line 123, in _replace_tuning
    theo_int = interval_dict[note_sym] - interval_dict[tnc_sym]
KeyError: None
```

It seems the ```note_sym``` somehow becomes ```None``` in some cases.

**Comment by sertansenturk** [comment]
They complete list of failed scores: http://dunya.compmusic.upf.edu/document/manager/unprocessed/makam-symbtr/75

**Comment by hsercanatli** [comment]
@sertansenturk, I've tested the [extractor](https://github.com/MTG/pycompmusic/blob/master/compmusic/extractors/makam/scoresynthesis.py) on a small dataset (25 different scores include some examples reported at [Dunya](http://dunya.compmusic.upf.edu/document/manager/unprocessed/makam-symbtr/75)) on my local machine. It seems that the bug is fixed. We can ask Andres to rerun the code.
